import asyncio
import json
import logging
from typing import Callable, List

from .base import ProviderBase, register

logger = logging.getLogger(__name__)

@register
class DummyProvider(ProviderBase):
    name = "dummy"

    async def _run(self, messages: list, is_cancelled_callback: Callable[[], bool] = None) -> str:
        """Simulates a non-blocking network call that can be cancelled."""
        logger.info(f"DummyProvider: Simulating network latency for 2 seconds...")

        # Simulate a 2-second operation in small, cancellable chunks.
        for _ in range(20):  # 20 * 0.1s = 2s
            if is_cancelled_callback and is_cancelled_callback():
                logger.info("DummyProvider: Cancellation requested. Aborting simulation.")
                raise asyncio.CancelledError("DummyProvider simulation cancelled.")
            await asyncio.sleep(0.1)

        logger.info("DummyProvider: Simulation finished. Returning mock data.")
        return json.dumps({
            "target_directory": "/DUMMY/INVOICES/",
            "target_filename": "dummy_invoice_20250101.pdf",
            "headline": "Dummy Invoice",
            "specifier": "Test Data",
            "context": "This is a dummy document for testing purposes.",
            "yyyymmdd": "20250101",
            "comment": "This was generated by the DummyProvider.",
            "keywords": ["dummy", "test", "invoice"]
        })
